name: Bug Report
description: バグの報告
title: "[bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: reproduction
    attributes:
      label: 再現手順
      description: バグを再現するための手順を教えてください。
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: 本来どのような動作をすべきですか？
  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
      description: 実際にはどのような動作をしましたか？
